# Generated by Django 3.2.5 on 2021-07-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_name', models.CharField(max_length=40)),
                ('students_age', models.IntegerField()),
                ('students_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
