# Generated by Django 3.2.5 on 2021-07-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='students_password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='students_age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='students',
            name='students_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='students',
            name='students_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
