# Generated by Django 3.2.5 on 2021-07-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_auto_20210730_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='students_age',
            field=models.IntegerField(),
        ),
    ]
