# Generated by Django 3.2.5 on 2021-07-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_alter_students_students_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='students_age',
            field=models.IntegerField(),
        ),
    ]
